# Generated by Django 2.2.6 on 2019-12-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='메일 제목')),
                ('description', models.TextField(verbose_name='메일 내용')),
                ('writer', models.CharField(max_length=10, verbose_name='메일 작성자')),
                ('writer_email', models.EmailField(max_length=30, verbose_name='작성자 아이디')),
                ('attn_email', models.EmailField(max_length=30, verbose_name='받는사람 아이디')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='작성일자')),
            ],
        ),
    ]
