# Generated by Django 2.2.5 on 2019-11-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=10, verbose_name='강의명')),
                ('title', models.CharField(max_length=10, verbose_name='제목')),
                ('description', models.TextField(verbose_name='내용')),
                ('writer', models.CharField(max_length=10, verbose_name='작성자')),
                ('date', models.DateField(auto_now=True, verbose_name='작성일')),
            ],
        ),
        migrations.CreateModel(
            name='Grade_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10, verbose_name='학년')),
                ('title', models.CharField(max_length=10, verbose_name='제목')),
                ('description', models.TextField(verbose_name='내용')),
                ('writer', models.CharField(max_length=10, verbose_name='작성자')),
                ('date', models.DateField(auto_now=True, verbose_name='작성일')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('email', models.CharField(max_length=30, verbose_name='아이디')),
                ('professor_number', models.CharField(max_length=10, verbose_name='직원번호')),
                ('password', models.CharField(max_length=20, verbose_name='비밀번호')),
            ],
        ),
        migrations.CreateModel(
            name='Professor_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_name', models.CharField(max_length=10, verbose_name='지도교수')),
                ('title', models.CharField(max_length=10, verbose_name='제목')),
                ('description', models.TextField(verbose_name='내용')),
                ('writer', models.CharField(max_length=10, verbose_name='작성자')),
                ('date', models.DateField(auto_now=True, verbose_name='작성일')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('email', models.CharField(max_length=30, verbose_name='아이디')),
                ('student_number', models.CharField(max_length=10, verbose_name='학번')),
                ('password', models.CharField(max_length=20, verbose_name='비밀번호')),
                ('grade', models.CharField(max_length=10, verbose_name='학년')),
                ('tutor', models.CharField(max_length=10, verbose_name='지도교수')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20, verbose_name='게시판 종류')),
            ],
        ),
    ]
