# Generated by Django 2.2.6 on 2019-12-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='file_post',
            field=models.ManyToManyField(blank=True, related_name='학생파일업로드', to='web.Post', verbose_name='파일명'),
        ),
        migrations.AddField(
            model_name='student',
            name='like_post',
            field=models.ManyToManyField(blank=True, related_name='학생추천수', to='web.Post', verbose_name='추천수'),
        ),
        migrations.AddField(
            model_name='professor',
            name='file_post',
            field=models.ManyToManyField(blank=True, related_name='교수파일업로드', to='web.Post', verbose_name='파일명'),
        ),
        migrations.AddField(
            model_name='professor',
            name='like_post',
            field=models.ManyToManyField(blank=True, related_name='교수추천수', to='web.Post', verbose_name='추천수'),
        ),
    ]
