# Generated by Django 2.2.6 on 2019-12-01 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=20, verbose_name='게시판 이름')),
            ],
        ),
        migrations.CreateModel(
            name='BoardTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_type', models.CharField(max_length=20, verbose_name='상위 게시판이름')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('description', models.TextField(verbose_name='글 내용')),
                ('writer', models.CharField(max_length=10, verbose_name='작성자')),
                ('writer_email', models.EmailField(max_length=30, verbose_name='작성자 아이디')),
                ('date', models.DateField(auto_now=True, verbose_name='작성일')),
                ('board_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Board')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='board',
            name='board_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.BoardTable'),
        ),
    ]
