# Generated by Django 2.2.6 on 2019-12-12 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=20, verbose_name='게시판 이름')),
                ('supervisor', models.CharField(max_length=10, verbose_name='지도 교수')),
                ('grade', models.CharField(max_length=10, verbose_name='학년')),
            ],
        ),
        migrations.CreateModel(
            name='BoardTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_type', models.CharField(max_length=20, verbose_name='상위 게시판이름')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('description', models.TextField(verbose_name='글 내용')),
                ('writer', models.CharField(max_length=10, verbose_name='작성자')),
                ('writer_email', models.EmailField(max_length=30, verbose_name='작성자 아이디')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='작성일')),
                ('like_number', models.PositiveIntegerField(default=0, verbose_name='추천수')),
                ('board_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Board', verbose_name='게시판 이름')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Professor', verbose_name='교수')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Student', verbose_name='학생')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Uploaded_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='파일명')),
                ('writer', models.CharField(max_length=10, verbose_name='작성자')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Post', verbose_name='글 제목')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(verbose_name='댓글 내용')),
                ('writer', models.CharField(max_length=10, verbose_name='작성자')),
                ('writer_email', models.EmailField(max_length=30, verbose_name='작성자 아이디')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Post', verbose_name='글 제목')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='board_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.BoardTable', verbose_name='하위 게시판이름'),
        ),
    ]
